### ISSUE TITLE
Delivering deployment scripts as a separate project

### ISSUE THREAD

**Issue by albinohrn** [sitevision/webapp-boilerplate#11]
Hi!

Have you thought about delivering the deployment scripts as a separate project, that can be `npm` installed in any other project instead of being part in the source? Look at [create-react-app](https://github.com/facebook/create-react-app) for inspiration.

That way you could improve the scripts and users of them can easily upgrade to the latest version.

Keep up the good work! :)

**Comment by robinlagren** [comment]
Sounds like a plan, will definitely look into it.

**Comment by robinlagren** [comment]
https://github.com/sitevision/sitevision-scripts
